name: install-slicer
author: Sebastien Goll (Kitware SAS)
description: Install 3D Slicer
inputs:
  version:
    description: Version of Slicer available at https://community.chocolatey.org/packages/3dslicer#versionhistory
    default: ''
outputs:
  slicer_folder:
    description: Installation folder for Slicer
    value: ${{ steps.slicer_folder.outputs.slicer_folder }}

runs:
  using: composite
  steps:
    - name: Setting the permission
      run: chmod +x "${{ github.action_path }}/downloader.sh"
      shell: bash
    - name: Download installer
      run: |
        "${{ github.action_path }}/downloader.sh" ${{ runner.os }}
      shell: bash
    - name: Get installer file
      id: installer
      run: |
        installer=$(find "./installer" -maxdepth 1 -name "Slicer*" | head -n1 | xargs realpath)
        echo "slicer_installer=$installer" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{runner.os == 'Windows'}}
      run: ${{ steps.installer.outputs.slicer_installer }} //S
      shell: bash
    - if: ${{runner.os == 'Windows'}}
      id: slicer_folder
      shell: bash
      run: |
        folder=$(find "C:/ProgramData/slicer.org" -maxdepth 1 -type d -name Slicer* -exec stat --format "%Y %n" {} + |sort -nr | head -n1 | cut -d' ' -f2-)
        echo "slicer_folder=$folder" >> $GITHUB_OUTPUT
    - name: Download installer
      if: ${{ runner.os == 'Linux' }}
      run: |
        echo "Not implemented yet"
        echo "File for install: ${{ steps.installer.outputs.slicer_installer }}"
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      id: mac_install
      run: |
        brew install expect
        chmod +x "${{ github.action_path }}/macos_installer.exp"
        MOUNT_POINT=$("${{ github.action_path }}/macos_installer.exp" ${{ steps.installer.outputs.slicer_installer }} | grep -o '/Volumes/[^ ]*'| tr -d '\r\n')
        cp -R "$MOUNT_POINT/Slicer.app" /Applications/
        hdiutil detach "$MOUNT_POINT"
        echo "slicer_folder=/Applications/Slicer.app/Contents" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      run: |
        "${{ steps.mac_install.outputs.slicer_folder }}/MacOS/Slicer" --testing --no-main-window
      shell: bash