name: install-slicer
author: Sebastien Goll (Kitware SAS)
description: Install 3D Slicer
inputs:
  version:
    description: Version of Slicer available at https://community.chocolatey.org/packages/3dslicer#versionhistory
    default: ''
outputs:
  slicer_folder:
    description: Installation folder for Slicer
    value: ${{ steps.slicer_folder.outputs.slicer_folder }}

runs:
  using: composite
  steps:
    - name: Download installer
      run: |
        "${{ github.action_path }}/downloader.sh" ${{ runner.os }}
      shell: bash
    - name: Get installer file
      id: installer
      run: |
        installer=$(find "./installer" -maxdepth 1 -name "Slicer*" | head -n1 | xargs realpath)
        echo "slicer_installer=$installer" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{runner.os == 'Windows'}}
      run: ${{ steps.installer.outputs.slicer_installer }} //S
      shell: bash
    - if: ${{runner.os == 'Windows'}}
      id: slicer_folder
      shell: bash
      run: |
        folder=$(find "C:/ProgramData/slicer.org" -maxdepth 1 -type d -name Slicer* -exec stat --format "%Y %n" {} + |sort -nr | head -n1 | cut -d' ' -f2-)
        echo "slicer_folder=$folder" >> $GITHUB_OUTPUT
    - name: Download installer
      if: ${{ runner.os == 'Linux' }}
      run: echo "Not implemented yet"
      shell: bash
    - if: ${{ runner.os == 'macOS' }}
      run: echo "Not implemented yet"
      shell: bash