name: install-slicer
author: Sebastien Goll (Kitware SAS)
description: Install 3D Slicer
inputs:
  version:
    description: Version of Slicer available at https://community.chocolatey.org/packages/3dslicer#versionhistory
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Set version flag
      id: version_flag
      run: |
        if [ "${{ inputs.version }}" == "latest"  ]; then
          echo "version_flag=" >> $GITHUB_OUTPUT
        else
          echo "version_flag='--version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install Slicer on WindowsOS
      if: ${{runner.os == 'Windows'}}
      run: choco install 3dslicer -y ${{ steps.version_flag.outputs.version_flag}}
      shell: bash
