name: install-slicer
author: Sebastien Goll (Kitware SAS)
description: Install 3D Slicer
inputs:
  version:
    description: Version of Slicer available at https://community.chocolatey.org/packages/3dslicer#versionhistory
    default: ''

runs:
  using: composite
  steps:
    - name: Install Slicer on WindowsOS
      if: ${{runner.os == 'Windows'}}
      run: choco install 3dslicer -y --version=${{ inputs.version }} --allowdowngrade
      shell: bash
