name: slicer-run-python-script
author: Kitware
description: slicer-run-python-script
inputs:
  slicer_dir:
    description: Slicer directory
    required: true
  script:
    description: Path to python to run
    required: true
  additional_arguments:
    description: Additional arguments for Slicer executable
    default: ''
runs:
  using: composite
  steps:
    - run: echo "Hello world"
      shell: bash
    - run: echo "${{inputs.slicer_dir}}"
      shell: bash
    - run: echo "${{inputs.script}}"
      shell: bash
    - run: echo "${{inputs.additional_arguments}}"
      shell: bash
    - run: "${{inputs.script}}/Slicer.exe" --testing
      shell: bash