name: Testing
run-name: ${{ github.event.pull_request.number && format('Pull request {0}', github.event.pull_request.number) || format('Commit {0}', github.sha) }}
on:
  push:
    branches:
      - main
      - unix-os-slicer-install
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Tests-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/install-slicer
        id: slicer_install
        name: Install Slicer
      - name: Install PyTorch module
        uses: ./.github/actions/slicer-run-python-script
        with:
          script: './.github/python_scripts/install_pytorch_module.py'
          slicer_dir: ${{ steps.slicer_install.outputs.slicer_folder }}
          additional_arguments: --no-main-window --no-splash
      - name: Install Python dependencies
        uses: ./.github/actions/slicer-run-python-script
        with:
          script: './.github/python_scripts/install_python_dependencies.py'
          slicer_dir: ${{ steps.slicer_install.outputs.slicer_folder }}
          additional_arguments: --no-main-window --no-splash
      - name: Run tests
        uses: ./.github/actions/slicer-run-python-tests
        with:
          slicer_dir: ${{ steps.slicer_install.outputs.slicer_folder }}
          additional_arguments: --testing --no-splash
          tests_root_path: './MultiverSeg/Testing/Python'
          tests_name_pattern: '*TestCase.py'
          module_paths: './MultiverSeg'
  Install-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am the linux runner"
        shell: bash
  Install-MacOS:
    runs-on: macos-latest
    steps:
      - run: echo "I am the mac runner"
        shell: bash


